
    /**
     * Generated from tools/generate_megido_chars_data.js     
    */
    export default [
    {
        "clock_type": "祖",
        "clock_id": 1,
        "name": "バエル",
        "style": "バースト",
        "class": "スナイパー",
        "regenerated": false,
        "main": true,
        "event": false,
        "terminus": false,
        "implemented": "2018-01-17",
        "id": "祖1"
    },
    {
        "clock_type": "祖",
        "clock_id": 2,
        "name": "アガレス",
        "style": "バースト",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖2"
    },
    {
        "clock_type": "祖",
        "clock_id": 2,
        "name": "アガレス",
        "style": "カウンター",
        "class": "スナイパー",
        "regenerated": true,
        "main": false,
        "event": true,
        "terminus": false,
        "implemented": "2019-10-30",
        "id": "祖2R"
    },
    {
        "clock_type": "祖",
        "clock_id": 3,
        "name": "ウァサゴ",
        "style": "ラッシュ",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖3"
    },
    {
        "clock_type": "祖",
        "clock_id": 4,
        "name": "ガミジン",
        "style": "カウンター",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖4"
    },
    {
        "clock_type": "祖",
        "clock_id": 5,
        "name": "マルバス",
        "style": "カウンター",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖5"
    },
    {
        "clock_type": "祖",
        "clock_id": 5,
        "name": "マルバス",
        "style": "ラッシュ",
        "class": "スナイパー",
        "regenerated": true,
        "main": false,
        "event": true,
        "terminus": false,
        "implemented": "2018-09-28",
        "id": "祖5R"
    },
    {
        "clock_type": "祖",
        "clock_id": 6,
        "name": "ウァレフォル",
        "style": "ラッシュ",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖6"
    },
    {
        "clock_type": "祖",
        "clock_id": 7,
        "name": "アモン",
        "style": "ラッシュ",
        "class": "ファイター",
        "regenerated": true,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2018-12-13",
        "id": "祖7R"
    },
    {
        "clock_type": "祖",
        "clock_id": 7,
        "name": "アモン",
        "style": "バースト",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖7"
    },
    {
        "clock_type": "祖",
        "clock_id": 8,
        "name": "バルバトス",
        "style": "ラッシュ",
        "class": "スナイパー",
        "regenerated": true,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2019-03-31",
        "id": "祖8R"
    },
    {
        "clock_type": "祖",
        "clock_id": 8,
        "name": "バルバトス",
        "style": "カウンター",
        "class": "スナイパー",
        "regenerated": false,
        "main": true,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖8"
    },
    {
        "clock_type": "祖",
        "clock_id": 9,
        "name": "パイモン",
        "style": "ラッシュ",
        "class": "ファイター",
        "regenerated": false,
        "main": true,
        "event": false,
        "terminus": false,
        "implemented": "2018-01-17",
        "id": "祖9"
    },
    {
        "clock_type": "祖",
        "clock_id": 10,
        "name": "ブエル",
        "style": "バースト",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖10"
    },
    {
        "clock_type": "祖",
        "clock_id": 11,
        "name": "グシオン",
        "style": "カウンター",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖11"
    },
    {
        "clock_type": "祖",
        "clock_id": 11,
        "name": "グシオン",
        "style": "バースト",
        "class": "スナイパー",
        "regenerated": true,
        "main": false,
        "event": true,
        "terminus": false,
        "implemented": "2019-07-05",
        "id": "祖11R"
    },
    {
        "clock_type": "祖",
        "clock_id": 12,
        "name": "シトリー",
        "style": "カウンター",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖12"
    },
    {
        "clock_type": "祖",
        "clock_id": 12,
        "name": "シトリー",
        "style": "ラッシュ",
        "class": "トルーパー",
        "regenerated": true,
        "main": false,
        "event": true,
        "terminus": false,
        "implemented": "2018-10-31",
        "id": "祖12R"
    },
    {
        "clock_type": "祖",
        "clock_id": 13,
        "name": "ベレト",
        "style": "カウンター",
        "class": "トルーパー",
        "regenerated": false,
        "main": true,
        "event": false,
        "terminus": false,
        "implemented": "2018-01-17",
        "id": "祖13"
    },
    {
        "clock_type": "祖",
        "clock_id": 14,
        "name": "レラジェ",
        "style": "カウンター",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2017-12-29",
        "id": "祖14"
    },
    {
        "clock_type": "祖",
        "clock_id": 14,
        "name": "レラジェ",
        "style": "ラッシュ",
        "class": "スナイパー",
        "regenerated": true,
        "main": false,
        "event": true,
        "terminus": false,
        "implemented": "2018-12-28",
        "id": "祖14R"
    },
    {
        "clock_type": "祖",
        "clock_id": 15,
        "name": "エリゴス",
        "style": "ラッシュ",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖15"
    },
    {
        "clock_type": "祖",
        "clock_id": 15,
        "name": "エリゴス",
        "style": "バースト",
        "class": "ファイター",
        "regenerated": true,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2019-09-10",
        "id": "祖15R"
    },
    {
        "clock_type": "祖",
        "clock_id": 16,
        "name": "ゼパル",
        "style": "ラッシュ",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖16"
    },
    {
        "clock_type": "祖",
        "clock_id": 16,
        "name": "ゼパル",
        "style": "カウンター",
        "class": "ファイター",
        "regenerated": true,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2018-09-11",
        "id": "祖16R"
    },
    {
        "clock_type": "祖",
        "clock_id": 17,
        "name": "ボティス",
        "style": "カウンター",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖17"
    },
    {
        "clock_type": "祖",
        "clock_id": 18,
        "name": "バティン",
        "style": "ラッシュ",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖18"
    },
    {
        "clock_type": "祖",
        "clock_id": 18,
        "name": "バティン",
        "style": "バースト",
        "class": "トルーパー",
        "regenerated": true,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2020-02-10",
        "id": "祖18R"
    },
    {
        "clock_type": "祖",
        "clock_id": 19,
        "name": "サレオス",
        "style": "バースト",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖19"
    },
    {
        "clock_type": "祖",
        "clock_id": 19,
        "name": "サレオス",
        "style": "カウンター",
        "class": "ファイター",
        "regenerated": true,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2020-01-14",
        "id": "祖19R"
    },
    {
        "clock_type": "祖",
        "clock_id": 20,
        "name": "プルソン",
        "style": "ラッシュ",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖20"
    },
    {
        "clock_type": "祖",
        "clock_id": 21,
        "name": "モラクス",
        "style": "バースト",
        "class": "ファイター",
        "regenerated": false,
        "main": true,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖21"
    },
    {
        "clock_type": "祖",
        "clock_id": 22,
        "name": "イポス",
        "style": "カウンター",
        "class": "ファイター",
        "regenerated": true,
        "main": false,
        "event": true,
        "terminus": false,
        "implemented": "2019-07-30",
        "id": "祖22R"
    },
    {
        "clock_type": "祖",
        "clock_id": 22,
        "name": "イポス",
        "style": "ラッシュ",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖22"
    },
    {
        "clock_type": "祖",
        "clock_id": 23,
        "name": "アイム",
        "style": "ラッシュ",
        "class": "スナイパー",
        "regenerated": true,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2019-08-11",
        "id": "祖23R"
    },
    {
        "clock_type": "祖",
        "clock_id": 23,
        "name": "アイム",
        "style": "バースト",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖23"
    },
    {
        "clock_type": "祖",
        "clock_id": 24,
        "name": "ナベリウス",
        "style": "ラッシュ",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖24"
    },
    {
        "clock_type": "祖",
        "clock_id": 25,
        "name": "グラシャラボラス",
        "style": "バースト",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖25"
    },
    {
        "clock_type": "祖",
        "clock_id": 26,
        "name": "ブネ",
        "style": "ラッシュ",
        "class": "ファイター",
        "regenerated": false,
        "main": true,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖26"
    },
    {
        "clock_type": "祖",
        "clock_id": 26,
        "name": "ブネ",
        "style": "バースト",
        "class": "ファイター",
        "regenerated": true,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2020-05-30",
        "id": "祖26R"
    },
    {
        "clock_type": "祖",
        "clock_id": 27,
        "name": "ロノウェ",
        "style": "カウンター",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖27"
    },
    {
        "clock_type": "祖",
        "clock_id": 28,
        "name": "ベリト",
        "style": "カウンター",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖28"
    },
    {
        "clock_type": "祖",
        "clock_id": 28,
        "name": "ベリト",
        "style": "バースト",
        "class": "ファイター",
        "regenerated": true,
        "main": false,
        "event": true,
        "terminus": false,
        "implemented": "2019-08-30",
        "id": "祖28R"
    },
    {
        "clock_type": "祖",
        "clock_id": 29,
        "name": "アスタロト",
        "style": "ラッシュ",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2017-12-19",
        "id": "祖29"
    },
    {
        "clock_type": "祖",
        "clock_id": 29,
        "name": "アスタロト",
        "style": "バースト",
        "class": "ファイター",
        "regenerated": true,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2018-11-15",
        "id": "祖29R"
    },
    {
        "clock_type": "祖",
        "clock_id": 30,
        "name": "フォルネウス",
        "style": "カウンター",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖30"
    },
    {
        "clock_type": "祖",
        "clock_id": 31,
        "name": "フォラス",
        "style": "バースト",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖31"
    },
    {
        "clock_type": "祖",
        "clock_id": 32,
        "name": "アスモデウス",
        "style": "バースト",
        "class": "ファイター",
        "regenerated": false,
        "main": true,
        "event": false,
        "terminus": false,
        "implemented": "2018-07-24",
        "id": "祖32"
    },
    {
        "clock_type": "祖",
        "clock_id": 33,
        "name": "ガープ",
        "style": "カウンター",
        "class": "ファイター",
        "regenerated": false,
        "main": true,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖33"
    },
    {
        "clock_type": "祖",
        "clock_id": 34,
        "name": "フルフル",
        "style": "バースト",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖34"
    },
    {
        "clock_type": "祖",
        "clock_id": 34,
        "name": "フルフル",
        "style": "カウンター",
        "class": "スナイパー",
        "regenerated": true,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2020-04-10",
        "id": "祖34R"
    },
    {
        "clock_type": "祖",
        "clock_id": 35,
        "name": "マルコシアス",
        "style": "バースト",
        "class": "スナイパー",
        "regenerated": true,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2018-12-07",
        "id": "祖35R"
    },
    {
        "clock_type": "祖",
        "clock_id": 35,
        "name": "マルコシアス",
        "style": "カウンター",
        "class": "スナイパー",
        "regenerated": false,
        "main": true,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖35"
    },
    {
        "clock_type": "祖",
        "clock_id": 36,
        "name": "ストラス",
        "style": "ラッシュ",
        "class": "トルーパー",
        "regenerated": true,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2019-05-17",
        "id": "祖36R"
    },
    {
        "clock_type": "祖",
        "clock_id": 36,
        "name": "ストラス",
        "style": "バースト",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖36"
    },
    {
        "clock_type": "祖",
        "clock_id": 37,
        "name": "フェニックス",
        "style": "カウンター",
        "class": "ファイター",
        "regenerated": true,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2019-07-15",
        "id": "祖37R"
    },
    {
        "clock_type": "祖",
        "clock_id": 37,
        "name": "フェニックス",
        "style": "バースト",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2017-12-19",
        "id": "祖37"
    },
    {
        "clock_type": "祖",
        "clock_id": 38,
        "name": "ハルファス",
        "style": "バースト",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖38"
    },
    {
        "clock_type": "祖",
        "clock_id": 39,
        "name": "マルファス",
        "style": "カウンター",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖39"
    },
    {
        "clock_type": "祖",
        "clock_id": 40,
        "name": "ラウム",
        "style": "カウンター",
        "class": "トルーパー",
        "regenerated": true,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2019-12-16",
        "id": "祖40R"
    },
    {
        "clock_type": "祖",
        "clock_id": 40,
        "name": "ラウム",
        "style": "バースト",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖40"
    },
    {
        "clock_type": "祖",
        "clock_id": 41,
        "name": "フォカロル",
        "style": "ラッシュ",
        "class": "トルーパー",
        "regenerated": true,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2019-11-10",
        "id": "祖41R"
    },
    {
        "clock_type": "祖",
        "clock_id": 41,
        "name": "フォカロル",
        "style": "バースト",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖41"
    },
    {
        "clock_type": "祖",
        "clock_id": 42,
        "name": "ウェパル",
        "style": "ラッシュ",
        "class": "トルーパー",
        "regenerated": false,
        "main": true,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖42"
    },
    {
        "clock_type": "祖",
        "clock_id": 42,
        "name": "ウェパル",
        "style": "バースト",
        "class": "トルーパー",
        "regenerated": true,
        "main": true,
        "event": false,
        "terminus": false,
        "implemented": "2018-10-04",
        "id": "祖42R"
    },
    {
        "clock_type": "祖",
        "clock_id": 43,
        "name": "サブナック",
        "style": "カウンター",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖43"
    },
    {
        "clock_type": "祖",
        "clock_id": 44,
        "name": "シャックス",
        "style": "カウンター",
        "class": "ファイター",
        "regenerated": false,
        "main": true,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖44"
    },
    {
        "clock_type": "祖",
        "clock_id": 44,
        "name": "シャックス",
        "style": "バースト",
        "class": "ファイター",
        "regenerated": true,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2019-12-07",
        "id": "祖44R"
    },
    {
        "clock_type": "祖",
        "clock_id": 45,
        "name": "ヴィネ",
        "style": "ラッシュ",
        "class": "スナイパー",
        "regenerated": true,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2018-10-10",
        "id": "祖45R"
    },
    {
        "clock_type": "祖",
        "clock_id": 45,
        "name": "ヴィネ",
        "style": "バースト",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖45"
    },
    {
        "clock_type": "祖",
        "clock_id": 46,
        "name": "ビフロンス",
        "style": "ラッシュ",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖46"
    },
    {
        "clock_type": "祖",
        "clock_id": 46,
        "name": "ビフロンス",
        "style": "カウンター",
        "class": "トルーパー",
        "regenerated": true,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2020-07-15",
        "id": "祖46R"
    },
    {
        "clock_type": "祖",
        "clock_id": 47,
        "name": "ウヴァル",
        "style": "ラッシュ",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖47"
    },
    {
        "clock_type": "祖",
        "clock_id": 48,
        "name": "ハーゲンティ",
        "style": "カウンター",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2017-12-29",
        "id": "祖48"
    },
    {
        "clock_type": "祖",
        "clock_id": 48,
        "name": "ハーゲンティ",
        "style": "バースト",
        "class": "トルーパー",
        "regenerated": true,
        "main": false,
        "event": true,
        "terminus": false,
        "implemented": "2018-11-27",
        "id": "祖48R"
    },
    {
        "clock_type": "祖",
        "clock_id": 49,
        "name": "クロケル",
        "style": "ラッシュ",
        "class": "スナイパー",
        "regenerated": true,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2019-04-15",
        "id": "祖49R"
    },
    {
        "clock_type": "祖",
        "clock_id": 49,
        "name": "クロケル",
        "style": "バースト",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖49"
    },
    {
        "clock_type": "祖",
        "clock_id": 50,
        "name": "フルカス",
        "style": "バースト",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖50"
    },
    {
        "clock_type": "祖",
        "clock_id": 51,
        "name": "バラム",
        "style": "カウンター",
        "class": "ファイター",
        "regenerated": false,
        "main": true,
        "event": false,
        "terminus": false,
        "implemented": "2018-06-29",
        "id": "祖51"
    },
    {
        "clock_type": "祖",
        "clock_id": 52,
        "name": "アロケル",
        "style": "カウンター",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖52"
    },
    {
        "clock_type": "祖",
        "clock_id": 53,
        "name": "カイム",
        "style": "カウンター",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖53"
    },
    {
        "clock_type": "祖",
        "clock_id": 54,
        "name": "ムルムル",
        "style": "ラッシュ",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖54"
    },
    {
        "clock_type": "祖",
        "clock_id": 55,
        "name": "オロバス",
        "style": "ラッシュ",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖55"
    },
    {
        "clock_type": "祖",
        "clock_id": 56,
        "name": "グレモリー",
        "style": "カウンター",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖56"
    },
    {
        "clock_type": "祖",
        "clock_id": 57,
        "name": "オセ",
        "style": "ラッシュ",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖57"
    },
    {
        "clock_type": "祖",
        "clock_id": 58,
        "name": "アミー",
        "style": "バースト",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖58"
    },
    {
        "clock_type": "祖",
        "clock_id": 59,
        "name": "オリアス",
        "style": "バースト",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2018-01-17",
        "id": "祖59"
    },
    {
        "clock_type": "祖",
        "clock_id": 59,
        "name": "オリアス",
        "style": "カウンター",
        "class": "スナイパー",
        "regenerated": true,
        "main": false,
        "event": true,
        "terminus": false,
        "implemented": "2019-11-22",
        "id": "祖59R"
    },
    {
        "clock_type": "祖",
        "clock_id": 60,
        "name": "ウァプラ",
        "style": "ラッシュ",
        "class": "トルーパー",
        "regenerated": true,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2019-06-15",
        "id": "祖60R"
    },
    {
        "clock_type": "祖",
        "clock_id": 60,
        "name": "ウァプラ",
        "style": "バースト",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖60"
    },
    {
        "clock_type": "祖",
        "clock_id": 61,
        "name": "ザガン",
        "style": "カウンター",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖61"
    },
    {
        "clock_type": "祖",
        "clock_id": 62,
        "name": "ウァラク",
        "style": "バースト",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖62"
    },
    {
        "clock_type": "祖",
        "clock_id": 63,
        "name": "アンドラス",
        "style": "ラッシュ",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖63"
    },
    {
        "clock_type": "祖",
        "clock_id": 63,
        "name": "アンドラス",
        "style": "カウンター",
        "class": "トルーパー",
        "regenerated": true,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2019-01-17",
        "id": "祖63R"
    },
    {
        "clock_type": "祖",
        "clock_id": 64,
        "name": "フラウロス",
        "style": "バースト",
        "class": "トルーパー",
        "regenerated": true,
        "main": false,
        "event": true,
        "terminus": false,
        "implemented": "2018-08-31",
        "id": "祖64R"
    },
    {
        "clock_type": "祖",
        "clock_id": 64,
        "name": "フラウロス",
        "style": "ラッシュ",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖64"
    },
    {
        "clock_type": "祖",
        "clock_id": 65,
        "name": "アンドレアルフス",
        "style": "ラッシュ",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": true,
        "terminus": false,
        "implemented": "2017-12-29",
        "id": "祖65"
    },
    {
        "clock_type": "祖",
        "clock_id": 66,
        "name": "キマリス",
        "style": "ラッシュ",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": true,
        "terminus": false,
        "implemented": "2017-12-11",
        "id": "祖66"
    },
    {
        "clock_type": "祖",
        "clock_id": 66,
        "name": "キマリス",
        "style": "カウンター",
        "class": "トルーパー",
        "regenerated": true,
        "main": false,
        "event": true,
        "terminus": false,
        "implemented": "2020-04-24",
        "id": "祖66R"
    },
    {
        "clock_type": "祖",
        "clock_id": 67,
        "name": "アムドゥスキアス",
        "style": "カウンター",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖67"
    },
    {
        "clock_type": "祖",
        "clock_id": 68,
        "name": "ベリアル",
        "style": "ラッシュ",
        "class": "スナイパー",
        "regenerated": false,
        "main": true,
        "event": false,
        "terminus": false,
        "implemented": "2018-05-24",
        "id": "祖68"
    },
    {
        "clock_type": "祖",
        "clock_id": 69,
        "name": "デカラビア",
        "style": "ラッシュ",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2018-01-17",
        "id": "祖69"
    },
    {
        "clock_type": "祖",
        "clock_id": 70,
        "name": "セーレ",
        "style": "カウンター",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖70"
    },
    {
        "clock_type": "祖",
        "clock_id": 71,
        "name": "ダンタリオン",
        "style": "バースト",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖71"
    },
    {
        "clock_type": "祖",
        "clock_id": 72,
        "name": "アンドロマリウス",
        "style": "ラッシュ",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": null,
        "id": "祖72"
    },
    {
        "clock_type": "真",
        "clock_id": 1,
        "name": "リリム",
        "style": "バースト",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2018-02-27",
        "id": "真1"
    },
    {
        "clock_type": "真",
        "clock_id": 1,
        "name": "リリム",
        "style": "ラッシュ",
        "class": "スナイパー",
        "regenerated": true,
        "main": false,
        "event": true,
        "terminus": false,
        "implemented": "2019-02-13",
        "id": "真1R"
    },
    {
        "clock_type": "真",
        "clock_id": 2,
        "name": "ニバス",
        "style": "ラッシュ",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2018-01-31",
        "id": "真2"
    },
    {
        "clock_type": "真",
        "clock_id": 2,
        "name": "ニバス",
        "style": "バースト",
        "class": "スナイパー",
        "regenerated": true,
        "main": false,
        "event": true,
        "terminus": false,
        "implemented": "2020-01-02",
        "id": "真2R"
    },
    {
        "clock_type": "真",
        "clock_id": 3,
        "name": "サキュバス",
        "style": "ラッシュ",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2018-02-27",
        "id": "真3"
    },
    {
        "clock_type": "真",
        "clock_id": 3,
        "name": "サキュバス",
        "style": "バースト",
        "class": "トルーパー",
        "regenerated": true,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2019-02-14",
        "id": "真3R"
    },
    {
        "clock_type": "真",
        "clock_id": 4,
        "name": "ユフィール",
        "style": "バースト",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": true,
        "implemented": "2018-01-31",
        "id": "真4"
    },
    {
        "clock_type": "真",
        "clock_id": 4,
        "name": "ユフィール",
        "style": "カウンター",
        "class": "スナイパー",
        "regenerated": true,
        "main": false,
        "event": false,
        "terminus": true,
        "implemented": "2020-04-30",
        "id": "真4R"
    },
    {
        "clock_type": "真",
        "clock_id": 5,
        "name": "フリアエ",
        "style": "カウンター",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2018-04-27",
        "id": "真5"
    },
    {
        "clock_type": "真",
        "clock_id": 6,
        "name": "アラストール",
        "style": "カウンター",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2018-05-10",
        "id": "真6"
    },
    {
        "clock_type": "真",
        "clock_id": 7,
        "name": "ヒュトギン",
        "style": "バースト",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": true,
        "terminus": false,
        "implemented": "2019-05-03",
        "id": "真7"
    },
    {
        "clock_type": "真",
        "clock_id": 9,
        "name": "インキュバス",
        "style": "ラッシュ",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2018-03-30",
        "id": "真9"
    },
    {
        "clock_type": "真",
        "clock_id": 9,
        "name": "インキュバス",
        "style": "カウンター",
        "class": "ファイター",
        "regenerated": true,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2019-03-15",
        "id": "真9R"
    },
    {
        "clock_type": "真",
        "clock_id": 10,
        "name": "グリマルキン",
        "style": "カウンター",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2019-01-01",
        "id": "真10"
    },
    {
        "clock_type": "真",
        "clock_id": 11,
        "name": "コルソン",
        "style": "カウンター",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2018-06-30",
        "id": "真11"
    },
    {
        "clock_type": "真",
        "clock_id": 12,
        "name": "ジニマル",
        "style": "カウンター",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": true,
        "terminus": false,
        "implemented": "2018-07-05",
        "id": "真12"
    },
    {
        "clock_type": "真",
        "clock_id": 13,
        "name": "バフォメット",
        "style": "ラッシュ",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2018-08-13",
        "id": "真13"
    },
    {
        "clock_type": "真",
        "clock_id": 14,
        "name": "サラ",
        "style": "ラッシュ",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2018-05-31",
        "id": "真14"
    },
    {
        "clock_type": "真",
        "clock_id": 15,
        "name": "サタナキア",
        "style": "ラッシュ",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2018-06-13",
        "id": "真15"
    },
    {
        "clock_type": "真",
        "clock_id": 15,
        "name": "サタナキア",
        "style": "バースト",
        "class": "スナイパー",
        "regenerated": true,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2020-03-11",
        "id": "真15R"
    },
    {
        "clock_type": "真",
        "clock_id": 17,
        "name": "ティアマト",
        "style": "カウンター",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2018-08-31",
        "id": "真17"
    },
    {
        "clock_type": "真",
        "clock_id": 18,
        "name": "ブニ",
        "style": "カウンター",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": true,
        "terminus": false,
        "implemented": "2018-04-13",
        "id": "真18"
    },
    {
        "clock_type": "真",
        "clock_id": 18,
        "name": "ブニ",
        "style": "バースト",
        "class": "ファイター",
        "regenerated": true,
        "main": false,
        "event": true,
        "terminus": false,
        "implemented": "2020-05-20",
        "id": "真18R"
    },
    {
        "clock_type": "真",
        "clock_id": 19,
        "name": "オリエンス",
        "style": "ラッシュ",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2019-10-31",
        "id": "真19"
    },
    {
        "clock_type": "真",
        "clock_id": 21,
        "name": "リヴァイアサン",
        "style": "バースト",
        "class": "スナイパー",
        "regenerated": false,
        "main": true,
        "event": false,
        "terminus": false,
        "implemented": "2019-10-28",
        "id": "真21"
    },
    {
        "clock_type": "真",
        "clock_id": 22,
        "name": "カスピエル",
        "style": "バースト",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": true,
        "terminus": false,
        "implemented": "2018-03-14",
        "id": "真22"
    },
    {
        "clock_type": "真",
        "clock_id": 22,
        "name": "カスピエル",
        "style": "カウンター",
        "class": "トルーパー",
        "regenerated": true,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2019-03-15",
        "id": "真22R"
    },
    {
        "clock_type": "真",
        "clock_id": 23,
        "name": "ネフィリム",
        "style": "カウンター",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": true,
        "implemented": "2020-01-01",
        "id": "真23"
    },
    {
        "clock_type": "真",
        "clock_id": 25,
        "name": "ニスロク",
        "style": "ラッシュ",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": true,
        "implemented": "2019-11-30",
        "id": "真25"
    },
    {
        "clock_type": "真",
        "clock_id": 26,
        "name": "オレイ",
        "style": "カウンター",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2020-04-21",
        "id": "真26"
    },
    {
        "clock_type": "真",
        "clock_id": 27,
        "name": "マルチネ",
        "style": "バースト",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2019-05-31",
        "id": "真27"
    },
    {
        "clock_type": "真",
        "clock_id": 28,
        "name": "アザゼル",
        "style": "ラッシュ",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2020-07-05",
        "id": "真28"
    },
    {
        "clock_type": "真",
        "clock_id": 31,
        "name": "フルーレティ",
        "style": "カウンター",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2019-08-31",
        "id": "真31"
    },
    {
        "clock_type": "真",
        "clock_id": 33,
        "name": "ハック",
        "style": "カウンター",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": true,
        "terminus": false,
        "implemented": "2019-06-01",
        "id": "真33"
    },
    {
        "clock_type": "真",
        "clock_id": 36,
        "name": "メフィスト",
        "style": "カウンター",
        "class": "スナイパー",
        "regenerated": true,
        "main": false,
        "event": true,
        "terminus": false,
        "implemented": "2019-03-12",
        "id": "真36R"
    },
    {
        "clock_type": "真",
        "clock_id": 36,
        "name": "メフィスト",
        "style": "バースト",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2018-03-22",
        "id": "真36"
    },
    {
        "clock_type": "真",
        "clock_id": 38,
        "name": "アガリアレプト",
        "style": "バースト",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": true,
        "terminus": false,
        "implemented": "2018-02-14",
        "id": "真38"
    },
    {
        "clock_type": "真",
        "clock_id": 38,
        "name": "アガリアレプト",
        "style": "ラッシュ",
        "class": "ファイター",
        "regenerated": true,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2019-02-14",
        "id": "真38R"
    },
    {
        "clock_type": "真",
        "clock_id": 41,
        "name": "アマイモン",
        "style": "カウンター",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2018-07-13",
        "id": "真41"
    },
    {
        "clock_type": "真",
        "clock_id": 43,
        "name": "サルガタナス",
        "style": "バースト",
        "class": "スナイパー",
        "regenerated": false,
        "main": true,
        "event": false,
        "terminus": false,
        "implemented": "2019-04-30",
        "id": "真43"
    },
    {
        "clock_type": "真",
        "clock_id": 49,
        "name": "サタナイル",
        "style": "バースト",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": true,
        "terminus": false,
        "implemented": "2019-04-02",
        "id": "真49"
    },
    {
        "clock_type": "真",
        "clock_id": 50,
        "name": "シャミハザ",
        "style": "カウンター",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": true,
        "terminus": false,
        "implemented": "2018-04-27",
        "id": "真50"
    },
    {
        "clock_type": "真",
        "clock_id": 51,
        "name": "プルフラス",
        "style": "ラッシュ",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": true,
        "terminus": false,
        "implemented": "2018-06-01",
        "id": "真51"
    },
    {
        "clock_type": "真",
        "clock_id": 51,
        "name": "プルフラス",
        "style": "バースト",
        "class": "ファイター",
        "regenerated": true,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2020-02-29",
        "id": "真51R"
    },
    {
        "clock_type": "真",
        "clock_id": 52,
        "name": "ジズ",
        "style": "バースト",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": true,
        "terminus": false,
        "implemented": "2018-08-02",
        "id": "真52"
    },
    {
        "clock_type": "真",
        "clock_id": 53,
        "name": "ベバル",
        "style": "バースト",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2019-09-30",
        "id": "真53"
    },
    {
        "clock_type": "真",
        "clock_id": 54,
        "name": "アバラム",
        "style": "バースト",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2019-10-11",
        "id": "真54"
    },
    {
        "clock_type": "真",
        "clock_id": 55,
        "name": "アリトン",
        "style": "カウンター",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2018-04-14",
        "id": "真55"
    },
    {
        "clock_type": "真",
        "clock_id": 57,
        "name": "ベヒモス",
        "style": "ラッシュ",
        "class": "ファイター",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": true,
        "implemented": "2018-11-30",
        "id": "真57"
    },
    {
        "clock_type": "真",
        "clock_id": 58,
        "name": "ダゴン",
        "style": "カウンター",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": true,
        "implemented": "2018-09-28",
        "id": "真58"
    },
    {
        "clock_type": "真",
        "clock_id": 59,
        "name": "スコルベノト",
        "style": "カウンター",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2020-01-31",
        "id": "真59"
    },
    {
        "clock_type": "真",
        "clock_id": 62,
        "name": "インプ",
        "style": "バースト",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2018-10-31",
        "id": "真62"
    },
    {
        "clock_type": "真",
        "clock_id": 63,
        "name": "アマゼロト",
        "style": "ラッシュ",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": false,
        "implemented": "2020-03-31",
        "id": "真63"
    },
    {
        "clock_type": "真",
        "clock_id": 64,
        "name": "プロメテウス",
        "style": "バースト",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": true,
        "implemented": "2018-07-31",
        "id": "真64"
    },
    {
        "clock_type": "真",
        "clock_id": 65,
        "name": "ベルフェゴール",
        "style": "カウンター",
        "class": "ファイター",
        "regenerated": false,
        "main": true,
        "event": false,
        "terminus": false,
        "implemented": "2019-08-26",
        "id": "真65"
    },
    {
        "clock_type": "真",
        "clock_id": 68,
        "name": "ネルガル",
        "style": "カウンター",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": true,
        "implemented": "2019-01-01",
        "id": "真68"
    },
    {
        "clock_type": "真",
        "clock_id": 69,
        "name": "バールゼフォン",
        "style": "バースト",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": true,
        "implemented": "2019-04-30",
        "id": "真69"
    },
    {
        "clock_type": "真",
        "clock_id": 70,
        "name": "アスラフィル",
        "style": "ラッシュ",
        "class": "トルーパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": true,
        "implemented": "2019-06-30",
        "id": "真70"
    },
    {
        "clock_type": "真",
        "clock_id": 71,
        "name": "アクィエル",
        "style": "カウンター",
        "class": "スナイパー",
        "regenerated": false,
        "main": false,
        "event": false,
        "terminus": true,
        "implemented": "2019-07-31",
        "id": "真71"
    }
];
    